version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
    - ../data:/var/lib/postgresql/data

  app:
    image: track
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@db:5432"
    ports:
    - 8080:8080
    links:
      - db