openapi: 3.0.1
info:
  title: Tracking API
  version: 1.0.0
  description:
    <p>An API for CRUD of sample tracking information
servers:
  - url: http://tracking-api-service/api/v1
paths:
  /files/{md5sum}:
    get:
      description: Return a file based on a file md5sum.
      parameters:
        - name: md5sum
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /samples/{id}/files:
    get:
      description: Return a list of files associated with a sample.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Add a new file to be associated with a sample.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: uri for the newly added file
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        404:
          description: Not found (sample not found)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        409:
          description: Already existed (with same md5sum)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /samples/{id}/files/{md5sum}:
    get:
      description: Return a file with {md5sum} associated with a sample with {id}.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: md5sum
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/File'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Delete a sample based on a sample ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: md5sum
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Deleted
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    File:
      type: object
      required:
        - md5sum
        - filename
        - file-type
      properties:
        md5sum:
          type: string
        filename:
          type: string
        file-type:
          type: string
          enum:
            - fastq
            - vcf
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string