# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Status(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, de_contamination=None, qc=None, variant_calling=None, prediction=None, bigsi_building=None, distance_calculation=None, stage=None):  # noqa: E501
        """Status - a model defined in OpenAPI

        :param de_contamination: The de_contamination of this Status.  # noqa: E501
        :type de_contamination: str
        :param qc: The qc of this Status.  # noqa: E501
        :type qc: str
        :param variant_calling: The variant_calling of this Status.  # noqa: E501
        :type variant_calling: str
        :param prediction: The prediction of this Status.  # noqa: E501
        :type prediction: str
        :param bigsi_building: The bigsi_building of this Status.  # noqa: E501
        :type bigsi_building: str
        :param distance_calculation: The distance_calculation of this Status.  # noqa: E501
        :type distance_calculation: str
        :param stage: The stage of this Status.  # noqa: E501
        :type stage: str
        """
        self.openapi_types = {
            'de_contamination': str,
            'qc': str,
            'variant_calling': str,
            'prediction': str,
            'bigsi_building': str,
            'distance_calculation': str,
            'stage': str
        }

        self.attribute_map = {
            'de_contamination': 'de-contamination',
            'qc': 'qc',
            'variant_calling': 'variant-calling',
            'prediction': 'prediction',
            'bigsi_building': 'bigsi-building',
            'distance_calculation': 'distance-calculation',
            'stage': 'stage'
        }

        self._de_contamination = de_contamination
        self._qc = qc
        self._variant_calling = variant_calling
        self._prediction = prediction
        self._bigsi_building = bigsi_building
        self._distance_calculation = distance_calculation
        self._stage = stage

    @classmethod
    def from_dict(cls, dikt) -> 'Status':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Status of this Status.  # noqa: E501
        :rtype: Status
        """
        return util.deserialize_model(dikt, cls)

    @property
    def de_contamination(self):
        """Gets the de_contamination of this Status.


        :return: The de_contamination of this Status.
        :rtype: str
        """
        return self._de_contamination

    @de_contamination.setter
    def de_contamination(self, de_contamination):
        """Sets the de_contamination of this Status.


        :param de_contamination: The de_contamination of this Status.
        :type de_contamination: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if de_contamination not in allowed_values:
            raise ValueError(
                "Invalid value for `de_contamination` ({0}), must be one of {1}"
                .format(de_contamination, allowed_values)
            )

        self._de_contamination = de_contamination

    @property
    def qc(self):
        """Gets the qc of this Status.


        :return: The qc of this Status.
        :rtype: str
        """
        return self._qc

    @qc.setter
    def qc(self, qc):
        """Sets the qc of this Status.


        :param qc: The qc of this Status.
        :type qc: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if qc not in allowed_values:
            raise ValueError(
                "Invalid value for `qc` ({0}), must be one of {1}"
                .format(qc, allowed_values)
            )

        self._qc = qc

    @property
    def variant_calling(self):
        """Gets the variant_calling of this Status.


        :return: The variant_calling of this Status.
        :rtype: str
        """
        return self._variant_calling

    @variant_calling.setter
    def variant_calling(self, variant_calling):
        """Sets the variant_calling of this Status.


        :param variant_calling: The variant_calling of this Status.
        :type variant_calling: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if variant_calling not in allowed_values:
            raise ValueError(
                "Invalid value for `variant_calling` ({0}), must be one of {1}"
                .format(variant_calling, allowed_values)
            )

        self._variant_calling = variant_calling

    @property
    def prediction(self):
        """Gets the prediction of this Status.


        :return: The prediction of this Status.
        :rtype: str
        """
        return self._prediction

    @prediction.setter
    def prediction(self, prediction):
        """Sets the prediction of this Status.


        :param prediction: The prediction of this Status.
        :type prediction: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if prediction not in allowed_values:
            raise ValueError(
                "Invalid value for `prediction` ({0}), must be one of {1}"
                .format(prediction, allowed_values)
            )

        self._prediction = prediction

    @property
    def bigsi_building(self):
        """Gets the bigsi_building of this Status.


        :return: The bigsi_building of this Status.
        :rtype: str
        """
        return self._bigsi_building

    @bigsi_building.setter
    def bigsi_building(self, bigsi_building):
        """Sets the bigsi_building of this Status.


        :param bigsi_building: The bigsi_building of this Status.
        :type bigsi_building: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if bigsi_building not in allowed_values:
            raise ValueError(
                "Invalid value for `bigsi_building` ({0}), must be one of {1}"
                .format(bigsi_building, allowed_values)
            )

        self._bigsi_building = bigsi_building

    @property
    def distance_calculation(self):
        """Gets the distance_calculation of this Status.


        :return: The distance_calculation of this Status.
        :rtype: str
        """
        return self._distance_calculation

    @distance_calculation.setter
    def distance_calculation(self, distance_calculation):
        """Sets the distance_calculation of this Status.


        :param distance_calculation: The distance_calculation of this Status.
        :type distance_calculation: str
        """
        allowed_values = ["pending", "started", "complete", "failed"]  # noqa: E501
        if distance_calculation not in allowed_values:
            raise ValueError(
                "Invalid value for `distance_calculation` ({0}), must be one of {1}"
                .format(distance_calculation, allowed_values)
            )

        self._distance_calculation = distance_calculation

    @property
    def stage(self):
        """Gets the stage of this Status.


        :return: The stage of this Status.
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this Status.


        :param stage: The stage of this Status.
        :type stage: str
        """
        allowed_values = ["accepted", "qc-failed", "live", "deprecated"]  # noqa: E501
        if stage not in allowed_values:
            raise ValueError(
                "Invalid value for `stage` ({0}), must be one of {1}"
                .format(stage, allowed_values)
            )

        self._stage = stage
